input {
  file {
		path => ["/home/ubuntu/bigdata/examples/elastic-stack/logs/log-generator*.log"]
		#exclude => "*.txt"
		start_position => "beginning" 
		sincedb_path => "/home/ubuntu/bigdata/examples/elastic-stack/logs/log-generator.sincedb"
		codec => multiline {
			pattern => "^(DEBUG|INFO|ERROR|TRACE|FATAL|WARN).*"
			negate => "true"
			what =>"previous"
		}
  }
}
output {
    stdout {
        #codec => json_lines
    }
}


