input {
  file {
		path => ["/home/ubuntu/examples/beats/FileBeat/log-generator*.log"]
		#exclude => "*.txt"
		start_position => "beginning" 
		sincedb_path => "/home/ubuntu/examples/beats/FileBeat/log-generator.sincedb"
  }
}
output {
    stdout {
        codec => json_lines
    }
}


