input {
  beats {
	port => 5044
  }
}

filter{
	grok{
		match => {"message" => ["%{WORD:nivel_traza} %{TIMESTAMP_ISO8601:fecha} \[%{WORD:hilo}\] %{JAVACLASS:clase} - %{WORD:tipo}\|%{NUMBER:respuesta}\|%{USERNAME:usuario}\|%{IP:ip}",
		"%{WORD:nivel_traza} %{TIMESTAMP_ISO8601:fecha} \[%{WORD:hilo}\] %{JAVACLASS:clase} - %{WORD:tipo}\|%{NUMBER:duration:float}\|%{DATA:accion}\|%{WORD:resultado}\|%{USERNAME:usuario}",
		"(?m)%{WORD:nivel_traza} %{TIMESTAMP_ISO8601:fecha} \[%{WORD:hilo}\] %{JAVACLASS:clase} - %{DATA:mensaje}\|%{GREEDYDATA:stacktrace}"]}
	}
	mutate{
		#convert => {"duration" => "integer"}#Se lo indicamos directamente en la expresion de Grok
		remove_field => ["message","prospector","input"]
		rename => {"@timestamp" => "processTime"}
	}
	
	if ![tipo]{#Si no existe el campo tipo
		mutate{
			add_field => {"tipo" => "JAVA_ERROR"}
		}
	}
	
	if [tipo]== "LOGIN"{
		mutate{
			convert => {"respuesta" => "integer"}
			add_field => {"login" => true}
		}
		
		if [respuesta]>300{
			mutate{
				replace => {"login" => false}
			}
		}
		
	}
	
	date{
		match => ["fecha","YYYY-MM-dd HH:mm:ss"]
	}
	
	
	
}
output {
    stdout {
        #codec => json_lines
    }
}


