input {
  beats {
	port => 5044
  }
}

filter{
	grok{
		match => {"message" => ["%{WORD:nivel_traza} %{TIMESTAMP_ISO8601:fecha} \[%{WORD:hilo}\] %{JAVACLASS:clase} - %{WORD:tipo}\|%{NUMBER:respuesta}\|%{USERNAME:usuario}\|%{IP:ip}",
		"%{WORD:nivel_traza} %{TIMESTAMP_ISO8601:fecha} \[%{WORD:hilo}\] %{JAVACLASS:clase} - %{WORD:tipo}\|%{NUMBER:duration}\|%{DATA:accion}\|%{WORD:resultado}\|%{USERNAME:usuario}",
		"(?m)%{WORD:nivel_traza} %{TIMESTAMP_ISO8601:fecha} \[%{WORD:hilo}\] %{JAVACLASS:clase} - %{DATA:mensaje}\|%{GREEDYDATA:stacktrace}"]  }
	}
}
output {
    stdout {
        #codec => json_lines
    }
}


