input {
  file {
    path => "/logs/application*.log"
    start_position => "beginning"
    sincedb_path   => "/usr/share/logstash/pipeline/.loggenerator.sincedb"
    #sincedb_path => "/dev/null"
    codec => multiline {
			pattern => "^(DEBUG|INFO|ERROR|FATAL|WARN).*"
			negate => "true"
			what =>"previous"
	} 
  }
}

filter{
	grok{
			match => {"message" => ["%{WORD:nivel_traza} %{TIMESTAMP_ISO8601:fecha} \[%{WORD:hilo}\] %{JAVACLASS:clase} - %{WORD:tipo}\|%{NUMBER:respuesta:float}\|(?<action>[^|]+)\|%{WORD:status}\|(?<user>[^|]+)\|%{NUMBER:latitude:float}\|%{NUMBER:longitude:float}",
			"%{WORD:nivel_traza} %{TIMESTAMP_ISO8601:fecha} \[%{WORD:hilo}\] %{JAVACLASS:clase} - %{INT:contador} - %{GREEDYDATA:tipo}" ,
			"%{LOGLEVEL:nivel_traza} %{TIMESTAMP_ISO8601:fecha} \[%{DATA:hilo}\] %{JAVACLASS:clase} - %{DATA:message}\|%{DATA:tipo}\|%{DATA:user}\|%{DATA:duration}s", 
			"%{LOGLEVEL:nivel_traza} %{TIMESTAMP_ISO8601:fecha} \[%{DATA:hilo}\] %{JAVACLASS:clase} - %{WORD:tipo}\|%{INT:status_code}\|(?<user>[^|]+)\|%{IPORHOST:client_ip}\|%{NUMBER:latitude:float}\|%{NUMBER:longitude:float}",
			"%{LOGLEVEL:nivel_traza} %{TIMESTAMP_ISO8601:fecha} \[%{DATA:hilo}\] %{JAVACLASS:clase} - %{DATA:message}\|%{GREEDYDATA:stacktrace}"
						]  }
	}
	mutate{
		#convert => {"duration" => "integer"}#Se lo indicamos directamente en la expresion de Grok
		remove_field => ["message","tags"]
		rename => {"@timestamp" => "processTime"}
	}
	
	if ![tipo]{#Si no existe el campo tipo
		mutate{
			add_field => {"tipo" => "JAVA_ERROR"}
		}
	}
	
	if [tipo] == "LOGIN" and [nivel_traza] == "INFO" {
		translate {
			field => "status_code"
			destination => "respuestaTexto"
			dictionary => {
				"200" => "Login Correcto"
				"201" => "Login tras varios intentos"
				"202" => "Login con actualizacion de datos"
				"204" => "Login automático"
				"250" => "Login recordado"
				"100" => "Usuario suplantado"
				"150" => "Usuario suplantado automaticamente"
				"400" => "Usuario bloqueado"
				"404" => "Usuario no encontrado"
				"500" => "Contraseña expirada"
			}
		}
		
		geoip{
			source => "client_ip"
		}
	}
	
	date{
		match => ["fecha","YYYY-MM-dd HH:mm:ss"]
		#target => "@timestamp"
	}
}

output {
  stdout {
    codec => rubydebug
    #codec => json_lines
  }
  elasticsearch{
	hosts => "es01:9200"
	index => "log-generator"
	#index => "log-generator-%{type}-%{+YYYY.MM.dd}"
  }
}
